Add TEMP_DIR variable and concept.
TEMP_DIR is used when LOG_DIR is not available. The enxt time when both
are available and jit is invoked, all files from TEMP_DIR will be copied
to LOG_DIR. When the copy succeeds the TEMP_DIR files will be deleted.

TEMP_DIR should be a local directory whereas LOG_DIR can be remote.

diff --git a/jit b/jit
--- a/jit
+++ b/jit
@@ -6,7 +6,7 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 CONFIG_FILE="$DIR/config.cfg"
 CONFIG_EXAMPLE="$DIR/config.example"
 
-if [ ! -f $CONFIG_FILE ]; then
+if [[ ! -f $CONFIG_FILE ]]; then
     cp $CONFIG_EXAMPLE $CONFIG_FILE
     read -p "Please edit your config file! [OK]"
     vim $CONFIG_FILE
@@ -14,11 +14,32 @@ fi
 
 . $CONFIG_FILE
 
-if [ ! -d $LOG_DIR ]; then
+if [[ ! -d $LOG_DIR ]]; then
     echo "Note: directory '$LOG_DIR' does not exist."
-    echo "Please create it manually or update the config file"
+    if [[ -d $TEMP_DIR ]]; then
+        printf "❗️ Using temp dir $TEMP_DIR instead. \nData will be synced to $LOG_DIR when it is available again.\n\n"
+        LOG_DIR=$TEMP_DIR
+    else
+        echo "🚫 Please create it manually or update the config file"
+        exit -2
+    fi
+else
+    echo "✅ Accessing jit directory '$LOG_DIR'"
 
-    exit -2
+
+    if [[ -d $TEMP_DIR ]]; then
+
+        NUM_FILES=$(ls -1q $TEMP_DIR | wc -l)
+        if [[ NUM_FILES -ge 1 ]]; then
+            echo "🚀 Moving $NUM_FILES files from $TEMP_DIR to $LOG_DIR"
+            cp $TEMP_DIR/*.md $LOG_DIR
+            if [[ $? -eq 0 ]]; then
+                rm $TEMP_DIR/*.md
+            else
+                echo '🚫 Copying failed..'
+            fi
+        fi
+    fi
 fi
 
 
